### ISSUE TITLE
Code Support

### ISSUE THREAD

**Issue by gpbmike** [webhook/webhook-redactor#4]
Trying to document code in the wysiwyg is very hard. It autoescapes everything so you can't edit it after the fact. It would be nice if it syntax highlighting and some form of tabbing could be used in these. Right now code highlighting needs to be done through JS on the frontend side. Would be amazing if the content somehow came over rendered so all we'd need is a css file.

From https://github.com/webhook/webhook-cms/issues/204

**Comment by snide** [comment]
Fixed. Doesn't support syntax highlighting yet.
